language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install coveralls --use-wheel"
  - "pip install -e ."
script:
  - coverage run --source=txtalert ./manage.py test --where=txtalert
after_success:
  - coveralls
