#!/bin/bash

PROJECT_NAME="txtalert"

PROJECT_HOME="$(dirname $0)"
cd $PROJECT_HOME

PROJECT_HOME="$PWD"
ENV_PATH=`expr "$PROJECT_HOME" : '\(/home/[^/]*/[^/]*\)'`

DJANGO_PATH="$ENV_PATH/env/django/1.0.2"
APPS_PATH="./apps"

. $ENV_PATH/bin/project_admin
