-- | therapyedge_clinic          | 
-- | therapyedge_contact         | 
-- | therapyedge_contact_msisdns | 
-- | therapyedge_importevent     | 
-- | therapyedge_language        | 
-- | therapyedge_msisdn          | 
-- | therapyedge_patient         | 
-- | therapyedge_pleasecallme    | 
-- | therapyedge_relation        | 
-- | therapyedge_visit           | 
-- | therapyedge_visitevent      | 
-- +-----------------------------+
-- 

-- FIXME's
-- 1. core_patient.deleted should be false by default
-- 2. core_patient.created_at should be autogenerated in sql
-- 3. core_patient.updated_at should be autogenerated in sql

-- therapyedge_clinic is now core_clinic, copy over data
DELETE FROM core_clinic;
INSERT INTO core_clinic SELECT * FROM therapyedge_clinic;

-- therapyedge_contact is no longer existing, it has been merged into core_patient
INSERT INTO core_patient (
        SELECT 
            id,
            te_id,
            active_msisdn_id,
            age,
            sex,
            opted_in,
            disclosed,
            deceased,
            last_clinic_id,
            risk_profile,
            language_id,
            0 as deleted,
            NOW() as created_at,
            NOW() as updated_at
        FROM therapyedge_contact 
        LEFT JOIN therapyedge_patient 
        ON therapyedge_contact.id = therapyedge_patient.contact_ptr_id
        WHERE therapyedge_patient.te_id IS NOT NULL -- make sure the join actually finds something to join
    );

-- copy over the therapyedge_language to core_language
DELETE FROM core_language; -- there's language junk in the initial_data fixture, get rid of it first
INSERT INTO core_language SELECT * FROM therapyedge_language;

-- copy over the therapyedge_msisdn to core_msisdn;
INSERT INTO core_msisdn SELECT * FROM therapyedge_msisdn;

-- copy over the please call me's
INSERT INTO core_pleasecallme SELECT * FROM therapyedge_pleasecallme;

-- copy over visit history data
INSERT INTO core_historicalvisit (
        SELECT
            therapyedge_visit.id,
            patient_id,
            te_id as te_visit_id,
            therapyedge_visitevent.date,
            therapyedge_visitevent.status,
            reason as comment,
            clinic_id,
            'unknown' as visit_type,
            0 as deleted,
            therapyedge_visitevent.date as created_at,
            therapyedge_visitevent.date as updated_at,
            NULL as history_id,
            therapyedge_visitevent.date as history_date,
            '~' as history_type
        FROM therapyedge_visitevent
        LEFT JOIN therapyedge_visit
        ON therapyedge_visitevent.visit_id = therapyedge_visit.id
        ORDER BY therapyedge_visitevent.id ASC -- get them in ascending order so our historical audittrail will somewhat stay intact
    );

-- get the latest core_historicalvisit and insert it into the core_visit as the 
-- latest version created
INSERT INTO core_visit (
        SELECT
            id,
            core_historicalvisit.patient_id,
            core_historicalvisit.te_visit_id,
            date,
            status,
            comment,
            clinic_id,
            visit_type,
            deleted,
            created_at,
            updated_at
        FROM core_historicalvisit
        RIGHT JOIN (
                SELECT patient_id, te_visit_id, MAX(history_id) as history_id
                FROM core_historicalvisit
                GROUP BY te_visit_id, patient_id
            ) AS history_ids
            ON history_ids.history_id = core_historicalvisit.history_id
    )
    
